api/auth.py
from flask import (Blueprint, flash, render_template, request, url_for, redirect) 
from werkzeug.security import generate_password_hash,check_password_hash
from .models import User
from .forms import LoginForm,RegisterForm
from flask_login import login_user, login_required,logout_user
from . import db

#create a blueprint
bp = Blueprint('auth', __name__)

@bp.route('/register', methods=['GET', 'POST'])
def register():
    register = RegisterForm()
    # if the form is validated
    if (register.validate_on_submit() == True):
            # get username, password and email from form
            uname = register.user_name.data
            pwd = register.password.data
            email = register.email_id.data
            # check if that user exists already
            u1 = User.query.filter_by(name=uname).first()
            if u1:
                flash('User name already exists, please login')
                return redirect(url_for('auth.login'))
            # create password hash
            pwd_hash = generate_password_hash(pwd)
            # user object creation
            new_user = User(name=uname, password_hash=pwd_hash, emailid=email)
            # db commit
            db.session.add(new_user)
            db.session.commit()
            # redirect to main page
            return redirect(url_for('main.index'))
    # the else is called when there is a get message
    else:
        return render_template('user.html', form=register, heading='Register')

# Login handling
@bp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    error=None
    if(login_form.validate_on_submit()==True):
        # get the username and password from the database
        user_name = login_form.user_name.data
        password = login_form.password.data
        u1 = User.query.filter_by(name=user_name).first()
        # if there is no user with that name
        if u1 is None:
            error='Incorrect user name'
        # check pwd
        elif not check_password_hash(u1.password_hash, password): # takes the hash and password
            error='Incorrect password'
        if error is None:
            # set login_user of flask_login to manage user
            login_user(u1)
            return redirect(url_for('main.index'))
        else:
            # flash an error on the html page if anything
            flash(error) 
    return render_template('user.html', form=login_form, heading='Login')

# Logout handling
@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

api/views.py
from flask import Blueprint, render_template, url_for, request, session, redirect
from flask_login import login_required, current_user

from website import events
from .models import Event, Ticket, User, Genre
from .forms import ProfileForm
from sqlalchemy import or_

bp = Blueprint('main', __name__)
   
# Route for main index page
@bp.route('/')
def index():
    events = Event.query.all() 
    genres = [e.value for e in Genre]
    user = current_user.get_id()
    return render_template('index.html', events=events, genres=genres, user=user)


# Route for profile ticket Page
@bp.route('/profile-tickets')
@login_required
def profileTickets():
    events = Event.query.all() 
    tickets = Ticket.query.filter_by(userId=current_user.get_id()).all() # correct ? distinct(eventId)
    return render_template('profile-tickets.html', tickets=tickets, events=events)

# Route for search fuctionality
@bp.route('/search')
def search():
    if request.args['search']:
        search_input = request.args['search']
        if (not search_input):
            return redirect(url_for('index'))
        else:
            dest = "%" + search_input + '%'
            location = "%" + search_input + '%'
            eventDescription = Event.query.filter(or_(Event.location.like(location), Event.description.like(dest), Event.status.like(dest), Event.genre.like(dest))).all() # add AND to check genre dropdown selection?
            return render_template('index.html', events=eventDescription)
    else:
        return redirect(url_for('main.index'))

api/templates/base.html
<!doctype html>
<html>

<head>
  <title>{% block title %}EventFest{% endblock %}</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{{ url_for('static', filename='styles/base.css') }}" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  {% block header %}{% endblock %}
</head>

<!-- Navbar -->
<header>
  <nav class="nav navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand navbar-title" href="{{url_for('main.index')}}">EventFest</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <!-- Separate navbar tabs -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{url_for('main.index')}}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('event.createEvent')}}">Create</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.profileTickets')}}">My Tickets</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <!-- Conditional for navbar login display -->
          {% if current_user.is_authenticated %}
          <li>
            <a class="nav-link active">Welcome {{current_user.name}}</a>
          </li>
          <li>
            <a class="nav-link active" href="{{ url_for('auth.logout') }}">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('auth.register') }}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('auth.login') }}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</header>

<body>
  {% block content %}{% endblock %}
</body>

<!-- Footer -->
<footer>
  <div class="footer-space row">
  </div>

  <footer class=" text-center text-lg-start bg-light text-muted">
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    </section>
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <div class="row mt-3">
          <div class="col-md-6 col-lg-2 col-xl-3 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4">
              EventFest
            </h6>
            <p>
              IAB 207 Rapid Web Development Assessment Task 3
            </p>
            <p>
              Monday 2pm-4pm Liam Group 12
            </p>
          </div>

          <div class="col-md-6 col-lg-2 col-xl-3">
            <h6 class="text-uppercase fw-bold mb-4">
              Navigation
            </h6>
            <p>
              <a href="{{url_for('main.index')}}" class="text-reset">Home</a>
            </p>
            <p>
              <a href="{{url_for('event.createEvent')}}" class="text-reset">Create Event</a>
            </p>
            <p>
              <a href="{{url_for('main.profileTickets')}}" class="text-reset">My Tickets</a>
            </p>
          </div>
          <div class="col-md-6 col-lg-4 col-xl-3">
            <h6 class="text-uppercase fw-bold mb-4">
              Github:
            </h6>
            <p> https://github.com/sh1ggy/iab207-ass3</p>
          </div>
          <div class="col-md-6 col-lg-4 col-xl-3 mx-auto mb-md-0 mb-4">
            <h6 class="text-uppercase fw-bold mb-4">
              Team Members
            </h6>
            <p>Peter Nguyen (n10229795)</p>
            <p>Rocco Wighton (n11000350)</p>
            <p>Ryan Evans-Schwede (n11068043)</p>
            <p>Tyrone Nolasco (n10232117)</p>
          </div>
        </div>
      </div>
    </section>

    <div class="navtext text-center p-4" style="background-color: rgba(33,37,41); color: white">
      ©IAB207 2021:
      <a class="navtext text-reset fw-bold" href="{{ url_for('main.index') }}">EventFest</a>
    </div>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
    crossorigin="anonymous"></script>
</html>

api/templates/error.html
{% extends "base.html" %}
{% block title %}Page Not Found{% endblock %}
{% block content %}
<!-- Error jumbotron -->
<link rel="stylesheet" href="{{ url_for('static', filename='styles/error.css') }}" />
<div class="jumbotron-image">
  <div class="p-5 rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold">Error {{error_code}}</h1>
      <p class="col-md-8 fs-4">{{error_message}}</p>
      <br>
      <br>
      <div class="row go-home-btn">
        <div class="go-home-btn">
          <p><a href="{{url_for('main.index')}}" class="btn btn-primary col-12">go somewhere nice</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

api/templates/index.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block header %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/index.css') }}" />
<script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js"
  integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous"
  async></script>
{% endblock %} {% block content %}
<!--Jumbotron for event image-->
<div class="jumbotron-image">
  <div class="p-5 rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold">Welcome,</h1>
      <p class="col-md-8 fs-4">
        EventFest is one of the biggest online booking system <br />
        for the hottest music festival near you! Browse from <br />
        up to eight different music genres of events or even <br />
        create your own events for everyone to come and party!

      </p>
    </div>
  </div>
</div>

<!-- Search -->
<div class="main bg-white">
  <div class="container">
    <div class="row justify-content-center mt-5 pb-4 search">
      <div class="col-md-10">
        <div class="card shadow p-5 mb-5 mh-100">
          <h1 class="text-center mb-3">Find our best music events</h1>
          <form class="form-inline d-flex flex-nowrap" action="{{url_for('main.search')}}">
            <div class="container">
              <div class="row justify-content-center">
                <div class="col-md-12 col-lg-7 my-1">
                  <input type="text" list="test" placeholder="Search, Select category" name="search"
                    class="search-input form-control flex-grow-1 w-100" id="SearchForm" />
                  <datalist id="test">
                    <!-- Show each genre in the dropdown for search -->
                    {% for genre in genres %}
                    <option value={{genre}}></option>
                    {% endfor %}
                  </datalist>
                </div>
                <div class="col-md-12 col-lg-2 my-1">
                  <button type="submit" class="btn btn-primary w-100">
                    Submit
                  </button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- Displaying all events -->
  <div class="container card-view">
    <div data-masonry='{"percentPosition": true }' class="row">
      {% for event in events %}
      <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3 my-4">
        <div class="event-card">
          <img src="{{event.image}}" class="card-img-top" style="height: 300px; object-fit: cover" alt="..." />
          <div class="card-body">
            <h3 class="card-title">{{event.title}}</h3>
            <!-- if statement to change status colour according to its value -->
            {% if event.status == 'Upcoming' %}
            <div class="status" style="background-color: rgba(0, 128, 0, 0.5)">
              <p class="status__text">{{event.status}}</p>
            </div>

            {% elif event.status == 'Booked' %}
            <div class="status" style="background-color: rgba(1, 25, 77, 0.575)">
              <p class="status__text">{{event.status}}</p>
            </div>
            {% elif event.status == 'Cancelled' %}
            <div class="status" style="background-color: rgba(155, 26, 32, 0.5)">
              <p class="status__text">{{event.status}}</p>
            </div>
            {% elif event.status == 'Inactive' %}
            <div class="status" style="background-color: rgba(104, 104, 104, 0.5)">
              <p class="status__text">{{event.status}}</p>
            </div>
            {% endif %}
            <p class="card-text">Genre: {{event.genre}}</p>
            <p class="card-text">Description: {{event.description}}</p>
            <p class="card-text">Artists: {{event.artists}}</p>
            <!-- Checking if the events shown was created by the current logged in user to display the edit button -->
            {% if event.creator == current_user.id %}
            <a href="{{ url_for('event.eventView', id=event.id) }}" style="margin-bottom:10px"
              class="btn btn-primary w-100">View</a>
            <a href="{{ url_for('event.editEvent', id=event.id) }}" class="btn btn-warning w-100">Edit</a>
            {% else %}
            <a href="{{ url_for('event.eventView', id=event.id) }}" class="btn btn-primary w-100">View</a>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  {% endblock %}
</div>

api/templates/profile-tickets.html
{% extends 'base.html' %}

{% block header %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/profile-tickets.css') }}" />
{% endblock %}

{% block content %}

<!-- Displaying user's tickets -->
<body>
  <br />
  <h1 class="primary-header text-center">My Tickets</h1>
  <br />
  <div class="main">
    <div class="card-group mx-5">
      <div class="card mx-3 my-5">
        <!-- checking for each tickets in the ticket database table -->
        {% for ticket in tickets %}
        <div class="ticket py-3 px-2 container-fluid">
          <div class="row align-items-center justify-content-center">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
              <h2 class="secondary-header pr-5 text-center font-weight-bold">
                {{ticket.event.name}}
              </h2>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-3 ticket-data">
              <img src={{ticket.event.image}} class='mx-auto d-block my-5' style="height: 200px">
            </div>
            <div class="col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3">
              <h4 class="text text-center">Date: {{ticket.event.startDate}}</h4>
            </div>
            <div class="col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3">
              <h4 class="text text-center">Qty: {{ticket.quantity}}</h4>
            </div>
            <div class="col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3">
              <h4 class="text text-center">Price: ${{ticket.event.ticketPrice}}</h4>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 ticket-data">
              <!-- Condition for different colours for status -->
              {% if ticket.event.status == 'Upcoming' %}
              <div class="ticket__status" style="background-color: rgba(0, 128, 0, 0.5);">
                <span>{{ticket.event.status}}</span>
              </div>
              {% elif ticket.event.status == 'Booked' %}
              <div class="ticket__status" style="background-color: rgba(1, 25, 77, 0.575)">
                <span>{{ticket.event.status}}</span>
              </div>
              {% elif ticket.event.status == 'Cancelled' %}
              <div class="ticket__status" style="background-color: rgba(155, 26, 32, 0.5)">
                <span>{{ticket.event.status}}</span>
              </div>
              {% elif ticket.event.status == 'Inactive' %}
              <div class="ticket__status" style="background-color: rgba(104, 104, 104, 0.5)">
                <span>{{ticket.event.status}}</span>
              </div>
              {% endif %}
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 ticket-data">
              <a href="{{ url_for('event.eventView', id=ticket.event.id) }}" class="btn btn-primary w-100 mt-2">View</a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
</body>
{% endblock %}

api/templates/user.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div class="container-fluid">
  <div class="page-header">
    <h4>{{heading}}</h4>
  </div>

  <!-- flashes any messages to the user -->
  {% with messages = get_flashed_messages() %}
  {% if messages %}
  <!-- check if there are any messages -->
  <div class="container-fluid">
    <div class="row mt-3 mb-3">
      <div class="col-md-12">
        {% for message in messages %}
        <!--loop through the messages-->
        <div class="alert alert-info">{{ message }}</div>
        <!--display as alert-->
        {% endfor %}
      </div>
    </div>
  </div>
  {% endif %}
  {% endwith %}

  <!-- Form rendering is simple and easy if using bootstrap -->

  <!-- When you have login form, then do show the user a link to register -->
  {% if heading|lower =='login' %}
  <div class="col-md-6 ml-5">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.user_name.label() }}
        {{ form.user_name(class="form-control form-control-lg") }}
      </div>
      <div class="form-group mb-2">
        {{ form.password.label() }}
        {{ form.password(class="form-control form-control-lg") }}
      </div>
      {{form.submit(class="btn btn-primary")}}
    </form>
  </div>
  <div class="col-md-4 mb-5 ml-5">
    <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
  </div>
  {% endif %}
  {% if heading|lower =='register' %}
  <div class="col-md-6 ml-5">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.user_name.label() }}
        {{ form.user_name(class="form-control form-control-lg") }}
      </div>
      <div class="form-group">
        {{ form.email_id.label() }}
        {{ form.email_id(class="form-control form-control-lg") }}
      </div>
      <div class="form-group">
        {{ form.password.label() }}
        {{ form.password(class="form-control form-control-lg") }}
      </div>
      <div class="form-group mb-2">
        {{ form.confirm.label() }}
        {{ form.confirm(class="form-control form-control-lg") }}
      </div>
      {{form.submit(class="btn btn-primary")}}
    </form>
  </div>
  <div class="col-md-4 mb-5 ml-5">
    <p>Already have an account? <a href="{{ url_for('auth.login') }}">Click here to login</a>.</p>
  </div>
  {% endif %}
</div>
{% endblock %}